/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_example_fibnative_FibLib.h"
#include<android/log.h>

static jlong fib(jlong n){
	return n<=0?0:n==1?1: fib(n-1)+fib(n-2);
}

JNIEXPORT jlong JNICALL Java_com_example_fibnative_FibLib_fibNR
  (JNIEnv *env, jclass cls, jlong n){
	__android_log_print(ANDROID_LOG_DEBUG, "DD_CPP","FibNR(%lld)",n);
	return fib( n);
}

JNIEXPORT jlong JNICALL Java_com_example_fibnative_FibLib_fibNI
  (JNIEnv *env, jclass cl, jlong n){
	__android_log_print(ANDROID_LOG_DEBUG, "DD_CPP","FibNI(%lld)",n);
	jlong prev = -1;
	jlong res = 1;
	jlong i =0;
	jlong sum =0;
	for( i=0;i<= n;i++){
		sum = res+ prev;
		prev = res;
		res = sum;
	}
	return res;
}

